# Generated by Django 5.0.6 on 2024-05-13 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.UUIDField()),
                ('sender_id', models.UUIDField()),
                ('user_name', models.CharField(max_length=255)),
                ('recipient_id', models.UUIDField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('attachments_json', models.TextField(blank=True, null=True)),
                ('first_attachment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('first_attachment_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('response_to', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
